ALTER TABLE public.products
  ADD COLUMN IF NOT EXISTS old_price NUMERIC,
  ADD COLUMN IF NOT EXISTS sku TEXT,
  ADD COLUMN IF NOT EXISTS tags JSONB DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS mfg TEXT,
  ADD COLUMN IF NOT EXISTS life TEXT,
  ADD COLUMN IF NOT EXISTS rating NUMERIC DEFAULT 5.0;
  