-- Corre este script en el editor SQL de Supabase para llenar tu tienda con productos de prueba

INSERT INTO public.categories (nombre, slug) VALUES
('Celulares', 'celulares'),
('Computación', 'computacion'),
('Tablets', 'tablets'),
('Consolas', 'consolas'),
('Monitores', 'monitores'),
('Periféricos', 'perifericos'),
('Audio', 'audio'),
('Componentes', 'componentes'),
('Muebles', 'muebles')
ON CONFLICT DO NOTHING;

INSERT INTO public.products (title, description, price, old_price, stock, sku, tags, mfg, life, rating, color, badge_text, badge_color, image_url, gallery_urls, category) VALUES
(
  'Apple iPhone 15 Pro 256GB',
  'El iPhone 15 Pro tiene un diseño de titanio aeroespacial y es el iPhone más ligero de la historia. Cuenta con el potente chip A17 Pro y un sistema de cámaras avanzado.',
  1200.00,
  1350.00,
  15,
  'IPH-15PRO-256-TIT',
  '["Smartphone", "Apple", "Nuevo"]'::jsonb,
  'Apple',
  '2 años',
  4.9,
  'Titanio Natural',
  'Nuevo Lanzamiento',
  'bg-blue-500 text-white',
  'https://images.unsplash.com/photo-1695048133142-1a20484d2569?q=80&w=400&auto=format&fit=crop',
  '[]'::jsonb,
  'Celulares'
),
(
  'MacBook Pro 14" M3 Pro',
  'Notebook Apple MacBook Pro 14 pulgadas con chip M3 Pro. Potencia para profesionales, diseño ultra delgado y batería de larga duración.',
  2400.00,
  2400.00,
  5,
  'MAC-PRO14-M3',
  '["Laptop", "Profesional", "Apple"]'::jsonb,
  'Apple',
  '3 años',
  5.0,
  'Gris Espacial',
  'Poco Stock',
  'bg-red-500 text-white',
  'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?q=80&w=400&auto=format&fit=crop',
  '[]'::jsonb,
  'Computación'
),
(
  'Samsung Galaxy S24 Ultra',
  'El smartphone con IA de Samsung. Incluye S-Pen integrado, pantalla de 6.8" plana y cámara principal de 200MP para fotos increíbles.',
  1350.00,
  1500.00,
  20,
  'SAM-S24U-512',
  '["Smartphone", "Android", "Samsung"]'::jsonb,
  'Samsung',
  '2 años',
  4.8,
  'Negro Titanio',
  NULL,
  NULL,
  'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?q=80&w=400&auto=format&fit=crop',
  '[]'::jsonb,
  'Celulares'
),
(
  'Monitor Gamer LG UltraGear 27"',
  'Monitor de 27 pulgadas IPS con 144Hz y tiempo de respuesta de 1ms. NVIDIA G-Sync compatible.',
  350.00,
  420.00,
  35,
  'LG-27GL850',
  '["Monitor", "Gamer", "144Hz"]'::jsonb,
  'LG',
  '5 años',
  4.7,
  'Negro',
  'Oferta Válida',
  'bg-green-500 text-white',
  'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?q=80&w=400&auto=format&fit=crop',
  '[]'::jsonb,
  'Monitores'
),
(
  'Sony PlayStation 5 Digital Edition',
  'Juega títulos de PS5 con gráficos asombrosos. Experiencia envolvente con memoria SSD ultrarrápida.',
  450.00,
  500.00,
  8,
  'PS5-DIGITAL',
  '["Consola", "Gaming", "Sony"]'::jsonb,
  'Sony',
  '5 años',
  4.9,
  'Blanco',
  'Hot Sale',
  'bg-orange-400 text-white',
  'https://images.unsplash.com/photo-1606813907291-d86efa9b94db?q=80&w=400&auto=format&fit=crop',
  '[]'::jsonb,
  'Consolas'
),
(
  'Teclado Mecánico Logitech G Pro X',
  'Teclado para juegos TKL diseñado para profesionales de eSports, con interruptores mecánicos intercambiables.',
  130.00,
  130.00,
  40,
  'LOGI-GPROX',
  '["Teclado", "Gamer", "Periféricos"]'::jsonb,
  'Logitech',
  '10 millones de clics',
  4.6,
  'Negro',
  NULL,
  NULL,
  'https://images.unsplash.com/photo-1595225476474-87563907a212?q=80&w=400&auto=format&fit=crop',
  '[]'::jsonb,
  'Periféricos'
),
(
  'Auriculares AirPods Pro 2',
  'Cancelación Activa de Ruido el doble de potente. Ahora con audio espacial personalizado.',
  249.00,
  299.00,
  100,
  'APP-PRO2',
  '["Audio", "Bluetooth", "Apple"]'::jsonb,
  'Apple',
  '2 años',
  4.9,
  'Blanco',
  NULL,
  NULL,
  'https://images.unsplash.com/photo-1600294037681-c80b4cb5b434?q=80&w=400&auto=format&fit=crop',
  '[]'::jsonb,
  'Audio'
),
(
  'Silla Gamer Secretlab Titan EVO 2022',
  'Comodidad ergonómica para largas sesiones de juego y trabajo. Tapizado en cuero sintético.',
  520.00,
  600.00,
  12,
  'SL-TITAN22',
  '["Muebles", "Gamer", "Ergonomía"]'::jsonb,
  'Secretlab',
  '5 años',
  4.8,
  'Negro/Rojo',
  'Envío Gratis',
  'bg-purple-500 text-white',
  'https://images.unsplash.com/photo-1598550476439-6847785fcea6?q=80&w=400&auto=format&fit=crop',
  '[]'::jsonb,
  'Muebles'
),
(
  'Disco SSD Samsung 980 PRO 1TB',
  'Velocidades de lectura de hasta 7,000 MB/s. Perfecto para gaming de alto rendimiento y PS5.',
  99.00,
  130.00,
  60,
  'SAM-980P-1T',
  '["Almacenamiento", "SSD", "PC"]'::jsonb,
  'Samsung',
  '10 años',
  4.9,
  'Negro',
  NULL,
  NULL,
  'https://images.unsplash.com/photo-1597848212624-a19eb35e2651?q=80&w=400&auto=format&fit=crop',
  '[]'::jsonb,
  'Componentes'
),
(
  'Tablet iPad Air 5ta Gen',
  'Chip M1 de Apple, pantalla Liquid Retina y compatibilidad con Apple Pencil 2.',
  599.00,
  599.00,
  25,
  'IPAD-AIR5-64',
  '["Tablet", "Apple", "Oficina"]'::jsonb,
  'Apple',
  '3 años',
  4.8,
  'Azul',
  NULL,
  NULL,
  'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?q=80&w=400&auto=format&fit=crop',
  '[]'::jsonb,
  'Tablets'
);
