
import './globals.css'
import { Suspense } from 'react'
import ThemeProvider from './ThemeProvider/ThemeProvider'
import { AuthProvider } from './context/AuthContext'


export const metadata = {
  title: 'Mi E-commerce',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="es">
      <body>
        <AuthProvider>
        <ThemeProvider>
          <Suspense fallback={<div className="p-6">Cargando...</div>}>
            {children}
          </Suspense>
        </ThemeProvider>
        </AuthProvider>
      </body>
    </html>
  )
}
